### ISSUE TITLE
no module name NN_data and Blosum62

### ISSUE THREAD

**Issue by wowfee** [XSLiuLab/TLimmuno2#1]
hello, 

Thank you very much for such a detailed model construction and data processing process, which allows me to try to reproduce your work, but I encountered some problems when building the BA model, when I execute these codes, 
**`from NN_data import NN_Data`
`from Blosum62 import blosum62`**
it reports that there are no these module, it seems that these are not modules that can be installed directly.
Could you give me any suggestion about this?
thank you in advance!

**Comment by GuangShuaiWang** [comment]
Thank you for your interest in my work. This mistake come from lacking these file. I have add them in `data` file.
and also you should change the file path when you use.

**Comment by wowfee** [comment]
Thank you for your reply !

I tried running TLimmuno2, and I have two small questions about the results:
1. The literature says _**A smaller rank or a higher score indicates stronger immunogenicity**_., I would like to know if there is a **recommended threshold** for the values of these two results to help judge?
2. For a single sequence, the predicted running time **exceeds 2 minutes** (without using the GPU). Is this normal?

Thanks in advance

**Comment by GuangShuaiWang** [comment]
1.You can find the IEDB recommended threshold in this link: [IEDB recommend rank](https://help.iedb.org/hc/en-us/articles/114094151811-Selecting-thresholds-cut-offs-for-MHC-class-I-and-II-binding-predictions), but in my paper I use rank 2% and score 0.426(ie, 500 nm).
2.I don't know you machine information. but in TLimmuno2 running process, it need calculate 90,000 background peptide to calculate rank value, it maybe time-consuming.

**Comment by wowfee** [comment]
Thanks for your help!
